# Generated by Django 4.2.1 on 2023-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
